WebApplication1/Controllers/BasketController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using System.Collections.Immutable;
using WebApplication1.Helpers;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly IProductRepository productRepository;
        private readonly IBaskRepository bask;
        private readonly IOrderRepository orderRepository;
        private readonly ICartItemDbRepository carts;
        private readonly ICompareProductDbRepository compareProducts;
        private readonly IFavoriteProductDbRepository favoriteProducts;
        private readonly UserManager<User> users;
        private readonly IMapper mapper;

        public BasketController(IProductRepository productRepository, IBaskRepository bask, IOrderRepository orderRepository, ICartItemDbRepository carts, UserManager<User> users, IMapper mapper)
        {
            this.productRepository = productRepository;
            this.bask = bask;
            this.orderRepository = orderRepository;
            this.carts = carts;
            this.users = users;
            this.mapper = mapper;
            this.mapper = mapper;
        }
        public async Task<IActionResult> AddsAsync(Guid productId)
        {
            var Prod = (await productRepository.GetAllAsync()).Where(x => x.Id == productId).First();
            var newProd = mapper.Map<ProductViewModel>(Prod);
            newProd.Images = await productRepository.GetProductImagesAsync(newProd.Id);
            bask.AddToCart(newProd);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Index()
        {
            var k = bask.GetCart().GroupBy(x => x.Id);
            bask.ClearResultProducts();
            foreach (var item in k)
            {
                var id = item.Key;
                var name = item.First().Name;
                var count = item.Count();
                var cost = item.First().Cost;
                var descr = item.First().Description;
                var newProd = new ProductViewModel(id, cost, name, descr, count);
                bask.AddToResultProducts(newProd);
            }
            var relustProductsOrdered = bask.GetResultProducts();
            relustProductsOrdered = relustProductsOrdered.OrderBy(x => x.Name).ToList();
            return View(relustProductsOrdered);
        }

        public IActionResult Clear()
        {
            bask.ClearCart();
            return RedirectToAction("Index");
        }

        public IActionResult Plus(Guid Id)
        {
            var prod = bask.GetCart().Where(x => x.Id == Id).First();
            bask.AddToCart(prod);
            return RedirectToAction("Index");
        }

        public IActionResult Minus(Guid Id)
        {
            bask.RemoveFromCart(Id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RegisterOrderAsync()
        {
            var resultBask = bask.GetResultProducts();
            ViewBag.Products = resultBask;
            ViewBag.ResultsCost = resultBask.Select(x => x.Cost * x.Count).Sum();
            var user = await users.FindByNameAsync(User.Identity.Name);
            ViewBag.user = user;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SuccessAsync(OrderViewModel order)
        {
            var orderDB = new Order();
            orderDB.User = await users.FindByNameAsync(User.Identity.Name);
            if (orderDB.User == null)
            {
                orderDB.Name = order.Name;
                orderDB.Number = order.Number;
                orderDB.Email = order.Email;
            }
            else
            {
                orderDB.Name = orderDB.User.UserName;
                orderDB.Number = orderDB.User.PhoneNumber;
                orderDB.Email = orderDB.User.Email;
            }
            var cart = bask.GetCart();
            orderDB.Total = bask.GetTotalCost();
            orderDB.Comments = order.Comments;
            orderDB.Address = order.Address;
            order.OrderCreation();
            orderDB.CreationDate = order.CreationDate;
            orderDB.CreationTime = order.CreationTime;
            orderDB.Status = order.Status;
            await orderRepository.AddAsync(orderDB);
            foreach (var product in cart)
            {
                await carts.AddAsync(orderDB.Id, product.Id);
            }
            bask.ClearResultProducts();
            bask.ClearCart();
            ViewBag.Products = await carts.GetOrdersCartsAsync(orderDB.Id);
            return View(orderDB);
        }
    }
}

WebApplication1/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB;
using OnlineShop.DB.Models;
using Serilog;
using WebApplication1.Helpers;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
	public class LoginController : Controller
	{
        private readonly UserManager<User> _usersManager;
        private readonly SignInManager<User> _signInManager;
        public LoginController(UserManager<User> usersManager, SignInManager<User> signInManager)
        {
            _usersManager = usersManager;
            _signInManager = signInManager;
        }
        public IActionResult Login(string ReturnUrl)
		{
			return View(new UserInfo() { ReturnUrl = ReturnUrl});
		}

		[HttpPost]
		public async Task<IActionResult> LoginAsync(UserInfo login)
		{
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(login.Name, login.Password, login.SaveUserInfo, false);
                if (result.Succeeded)
                {
                    return Redirect(login.ReturnUrl ?? "/Home");
                }
                else
                {
                    ModelState.AddModelError("", "Неправильное имя или пароль");
                }
            }
            return View(login);
        }

        public IActionResult Register(string? ReturnUrl)
        {
            return View(new UserRegViewModel() { ReturnUrl = ReturnUrl });
        }

        [HttpPost]
        public async Task<IActionResult> RegisterAsync(UserRegViewModel register)
        {
            if (register.Name == register.Password)
            {
                ModelState.AddModelError("", "Имя и пароль не должны совпадать");
            }
            if (ModelState.IsValid)
            {
                User user = new User { Email = register.Email, UserName = register.Name, PhoneNumber = register.Number, Age = register.Age };
                var result = await _usersManager.CreateAsync(user, register.Password);
                if (result.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    await _usersManager.AddToRoleAsync(user, Constants.UserRoleName);
                    return Redirect(register.ReturnUrl ?? "/Home");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(register);
        }

        [Authorize]
        public async Task<IActionResult> LogoutAsync()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

WebApplication1/Views/Shared/Components/Bask/BaskViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Helpers;

namespace WebApplication1.Views.Shared.Components.BaskComponents
{
    public class BaskViewComponent : ViewComponent
    {
        private readonly IBaskRepository bask;
        public BaskViewComponent(IBaskRepository bask)
        {
            this.bask = bask;
        }
        public IViewComponentResult Invoke()
        {
            int count = bask.GetCount();
            return View("Bask", count);
        }
    }
}

WebApplication1/Views/Shared/Components/UserImage/UserImageViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;

namespace WebApplication1.Views.Shared.Components.UserImage
{
    public class UserImageViewComponent : ViewComponent
    {
        private UserManager<User> UsersRepository;
        private IImageDbRepository imageDbRepository;
        public UserImageViewComponent(UserManager<User> usersRepository, IImageDbRepository imageDbRepository)
        {
            UsersRepository = usersRepository;
            this.imageDbRepository = imageDbRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await UsersRepository.FindByNameAsync(User.Identity.Name);
                var image = await imageDbRepository.GetUserImageAsync(user);
                return View("UserImage", image);
            }
            return View("UserImage", new Image());
        }
    }
}

WebApplication1/Views/Shared/Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - ShopCawkuncon - <a asp-area="" asp-controller="Home" asp-action="Index">About</a>
    </div>
</footer>

WebApplication1/Views/Shared/Header.cshtml
@using OnlineShop.DB
@using WebApplication1.Helpers;
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand ms-5" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-flex justify-content-end me-5">
                <ul class="navbar-nav d-flex">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">Корзина<sup>@await Component.InvokeAsync("Bask")</sup></a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Compare">Сравнение</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ShowFavorite">Избранное</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Выйти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">@await Component.InvokeAsync("UserImage")</a>
                        </li>
                    }
                    else
                    {
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">Регистрация</a>
                        </li>
                    }
                    @if (User.IsInRole(Constants.AdminRoleName))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Home" asp-action="Index">Администратор</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    @await Html.PartialAsync("Header")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("Footer")

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_ValidationScriptsPartial.cshtml")
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>