WebApplication1/Controllers/BasketController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineShop.DB.Models;
using System.Collections.Immutable;
using WebApplication1.Helpers;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        private readonly IProductRepository productRepository;
        private readonly IBaskRepository bask;
        private readonly IOrderRepository orderRepository;
        private readonly ICartItemDbRepository carts;
        private readonly ICompareProductDbRepository compareProducts;
        private readonly IFavoriteProductDbRepository favoriteProducts;
        private readonly UserManager<User> users;
        private readonly IMapper mapper;

        public BasketController(IProductRepository productRepository, IBaskRepository bask, IOrderRepository orderRepository, ICartItemDbRepository carts, UserManager<User> users, IMapper mapper)
        {
            this.productRepository = productRepository;
            this.bask = bask;
            this.orderRepository = orderRepository;
            this.carts = carts;
            this.users = users;
            this.mapper = mapper;
            this.mapper = mapper;
        }
        public async Task<IActionResult> AddsAsync(Guid productId)
        {
            var Prod = (await productRepository.GetAllAsync()).Where(x => x.Id == productId).First();
            var newProd = mapper.Map<ProductViewModel>(Prod);
            newProd.Images = await productRepository.GetProductImagesAsync(newProd.Id);
            bask.AddToCart(newProd);
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Index()
        {
            var k = bask.GetCart().GroupBy(x => x.Id);
            bask.ClearResultProducts();
            foreach (var item in k)
            {
                var id = item.Key;
                var name = item.First().Name;
                var count = item.Count();
                var cost = item.First().Cost;
                var descr = item.First().Description;
                var newProd = new ProductViewModel(id, cost, name, descr, count);
                bask.AddToResultProducts(newProd);
            }
            var relustProductsOrdered = bask.GetResultProducts();
            relustProductsOrdered = relustProductsOrdered.OrderBy(x => x.Name).ToList();
            return View(relustProductsOrdered);
        }

        public IActionResult Clear()
        {
            bask.ClearCart();
            return RedirectToAction("Index");
        }

        public IActionResult Plus(Guid Id)
        {
            var prod = bask.GetCart().Where(x => x.Id == Id).First();
            bask.AddToCart(prod);
            return RedirectToAction("Index");
        }

        public IActionResult Minus(Guid Id)
        {
            bask.RemoveFromCart(Id);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RegisterOrderAsync()
        {
            var resultBask = bask.GetResultProducts();
            ViewBag.Products = resultBask;
            ViewBag.ResultsCost = resultBask.Select(x => x.Cost * x.Count).Sum();
            var user = await users.FindByNameAsync(User.Identity.Name);
            ViewBag.user = user;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SuccessAsync(OrderViewModel order)
        {
            var orderDB = new Order();
            orderDB.User = await users.FindByNameAsync(User.Identity.Name);
            if (orderDB.User == null)
            {
                orderDB.Name = order.Name;
                orderDB.Number = order.Number;
                orderDB.Email = order.Email;
            }
            else
            {
                orderDB.Name = orderDB.User.UserName;
                orderDB.Number = orderDB.User.PhoneNumber;
                orderDB.Email = orderDB.User.Email;
            }
            var cart = bask.GetCart();
            orderDB.Total = bask.GetTotalCost();
            orderDB.Comments = order.Comments;
            orderDB.Address = order.Address;
            order.OrderCreation();
            orderDB.CreationDate = order.CreationDate;
            orderDB.CreationTime = order.CreationTime;
            orderDB.Status = order.Status;
            await orderRepository.AddAsync(orderDB);
            foreach (var product in cart)
            {
                await carts.AddAsync(orderDB.Id, product.Id);
            }
            bask.ClearResultProducts();
            bask.ClearCart();
            ViewBag.Products = await carts.GetOrdersCartsAsync(orderDB.Id);
            return View(orderDB);
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.CookiePolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using OnlineShop.DB;
using OnlineShop.DB.Models;
using System.Diagnostics;
using System.Linq.Expressions;
using System.Reflection.Metadata;
using WebApplication1.Helpers;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly IProductRepository productRepository;
        private readonly ICompareProductDbRepository prodCompare;
        private readonly ICompareProductDbRepository compareProducts;
        private readonly IFavoriteProductDbRepository favoriteProducts;
        private readonly IMapper mapper;
        private readonly IMemoryCache memoryCache;

        public HomeController(IProductRepository productRepository, ICompareProductDbRepository prodCompare, ICompareProductDbRepository compareProducts, IFavoriteProductDbRepository favoriteProducts, IMapper mapper, IMemoryCache memoryCache)
        {
            this.productRepository = productRepository;
            this.prodCompare = prodCompare;
            this.compareProducts = compareProducts;
            this.favoriteProducts = favoriteProducts;
            this.mapper = mapper;
            this.memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index()
        {
            memoryCache.TryGetValue<List<Product>>(Constants.ProductsCache, out var products);
            if (products == null)
            {
                products = await productRepository.GetAllAsync();
                var newCacheOptions = new MemoryCacheEntryOptions()
                {
                    AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(30),
                };
                memoryCache.Set(Constants.ProductsCache, products, newCacheOptions);
                foreach (var product in products)
                {
                    memoryCache.Set(product.Id, product, newCacheOptions);
                }
            }
            var newProducts = mapper.Map<List<ProductViewModel>>(products);
            newProducts.ForEach(prod => prod.Images = productRepository.GetProductImages(prod.Id));
            if (User.Identity.IsAuthenticated)
            {
                var idCompareProds = (await compareProducts.GetCompareProductsAsync(User.Identity.Name)).Select(pr => pr.Id);
                var idFavoriteProds = (await favoriteProducts.GetFavoriteProductsAsync(User.Identity.Name)).Select(pr => pr.Id);
                newProducts.ForEach(prod =>
                {
                    if (idCompareProds != null)
                    {
                        if (idCompareProds.Contains(prod.Id))
                        {
                            prod.ChangeCompare();
                        }
                    }
                    if (idFavoriteProds != null)
                    {
                        if (idFavoriteProds.Contains(prod.Id))
                        {
                            prod.ChangeFavorite();
                        }
                    }
                });
            }
            return View(newProducts);
        }
        [Authorize]
        public async Task<IActionResult> AddToComparsionAsync(Guid productId)
        {
            await prodCompare.AddAsync(productId, User.Identity.Name);
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> CompareAsync()
        {
            var products = await compareProducts.GetCompareProductsAsync(User.Identity.Name);
            var prods = mapper.Map<List<ProductViewModel>>(products);
            return View(prods);
        }
        [Authorize]
        public async Task<IActionResult> DeleteFromComparsionAsync(Guid productId)
        {
            await compareProducts.DeleteFromComparsionAsync(productId, User.Identity.Name);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> AddToFavoriteAsync(Guid productId)
        {
            await favoriteProducts.AddProdToFavorAsync(productId, User.Identity.Name);
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> DeleteFromFavoriteIndexAsync(Guid productId)
        {
            await favoriteProducts.DeleteFromFavoriteAsync(productId, User.Identity.Name);
            return RedirectToAction("Index");
        }
        [Authorize]
        public async Task<IActionResult> DeleteFromFavoriteAsync(Guid productId)
        {
            await favoriteProducts.DeleteFromFavoriteAsync(productId, User.Identity.Name);
            return RedirectToAction("ShowFavorite");
        }
        [Authorize]
        public async Task<IActionResult> ShowFavoriteAsync()
        {
            var prodToShow = await favoriteProducts.GetFavoriteProductsAsync(User.Identity.Name);
            var newListProd = mapper.Map<List<ProductViewModel>>(prodToShow);
            newListProd.ForEach(prod => prod.Images = productRepository.GetProductImages(prod.Id));
            var idCompareProds = (await compareProducts.GetCompareProductsAsync(User.Identity.Name)).Select(pr => pr.Id);
            var idFavoriteProds = (await favoriteProducts.GetFavoriteProductsAsync(User.Identity.Name)).Select(pr => pr.Id);
            newListProd.ForEach(prod =>
            {
                if (idCompareProds != null)
                {
                    if (idCompareProds.Contains(prod.Id))
                    {
                        prod.ChangeCompare();
                    }
                }
                if (idFavoriteProds != null)
                {
                    if (idFavoriteProds.Contains(prod.Id))
                    {
                        prod.ChangeFavorite();
                    }
                }
            });
            return View(newListProd);
        }

        [HttpPost]
        public async Task<IActionResult> SearchAsync(string search)
        {
            if (search == null || search == string.Empty)
            {
                return RedirectToAction(nameof(Index));
            }
            search = search.ToLower();
            memoryCache.TryGetValue<IEnumerable<Product>>(Constants.ProductsCache, out var result);
            if (result == null)
            {
                result = (await productRepository.GetAllAsync()).Where(x => x.Name.ToLower().Contains(search));
            }
            else
            {
                result = result.Where(x => x.Name.ToLower().Contains(search));
            }
            var resultProductViewModel = mapper.Map<List<ProductViewModel>>(result.ToList());
            resultProductViewModel.ForEach(product => product.Images = productRepository.GetProductImages(product.Id));
            return View(resultProductViewModel);
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using OnlineShop.DB;
using OnlineShop.DB.Models;
using WebApplication1.Helpers;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
		private readonly IProductRepository productRepository;
        private readonly IMapper mapper;
        private readonly IMemoryCache memoryCache;

        public ProductController(IProductRepository productRepository, IMapper mapper, IMemoryCache memoryCache)
        {
            this.productRepository = productRepository;
            this.mapper = mapper;
            this.memoryCache = memoryCache;
        }
        public IActionResult Index(Guid id)
        {
            memoryCache.TryGetValue(id, out Product product);
            if (product == null)
            {
                memoryCache.TryGetValue(Constants.ProductsCache, out List<Product> products);
                if (products != null)
                {
                    product = products.FirstOrDefault(pr => pr.Id == id);
                    if (product == null)
                    {
                        return NotFound();
                    }
                    var productView = mapper.Map<ProductViewModel>(product);
                    productView.Images = productRepository.GetProductImages(id);
                    return View(productView);
                }
            }
            else
            {
                var productView = mapper.Map<ProductViewModel>(product);
                productView.Images = productRepository.GetProductImages(id);
                return View(productView);
            }
            return View();
        }
    }
}

WebApplication1/Views/Shared/Components/Bask/BaskViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Helpers;

namespace WebApplication1.Views.Shared.Components.BaskComponents
{
    public class BaskViewComponent : ViewComponent
    {
        private readonly IBaskRepository bask;
        public BaskViewComponent(IBaskRepository bask)
        {
            this.bask = bask;
        }
        public IViewComponentResult Invoke()
        {
            int count = bask.GetCount();
            return View("Bask", count);
        }
    }
}

WebApplication1/Views/Home/Compare.cshtml
1@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<ProductViewModel>

@if (Model == null || Model.Count() == 0)
{   
            <div class="d-flex flex-column">
                <div class="d-flex  justify-content-center ">
                    <h2>Нет товаров для сравнения</h2>
                </div>
                <div class="d-flex  justify-content-center ">
                    <a asp-controller="Home" asp-action="Index" class="btn-active btn btn-light">На главную</a>
                </div>
            </div>
}
else
{
    <table>
        <tr>
            <td>Наименование</td>
            @foreach (var product in Model)
            {
                    <td>@product.Name</td>
            }
        </tr>
        <tr>
            <td>Цена</td>
            @foreach (var product in Model)
            {
                    <td>@product.Cost</td>
            }
        </tr>
        <tr>
            <td>Описание</td>
            @foreach (var product in Model)
            {
                    <td>@product.Description</td>
            }
        </tr>
        <tr>
            <td>Действие</td>
            @foreach (var product in Model)
            {
                <td><a asp-controller="Home" asp-action="DeleteFromComparsion" asp-route-productId="@product.Id" class="btn btn-danger">Удалить из сравнения</a></td>
            }

        </tr>
    </table>
}

WebApplication1/Views/Home/Index.cshtml
@using WebApplication1.Helpers;
@{
    ViewData["Title"] = "Home Page";
}

@model List<ProductViewModel>

    <div class="row">
        <div class="col-md-3 my-3">
            <div class="d-flex flex-column mb-2">
                <form method="post">
                    <div class="d-flex my-1">
                        <div class="input-group mb-3">
                          <input type="text" class="form-control" placeholder="Поиск по названию" aria-label="Поиск по названию" aria-describedby="basic-addon2" name="search">
                          <div class="input-group-append">
                              <button class="btn btn-outline-secondary" type="submit" asp-controller="Home" asp-action="Search"><i class="fa-solid fa-magnifying-glass"></i></button>
                          </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="d-flex flex-column mb-2">
                <div class="list-group">
                  <a class="list-group-item list-group-item-action active" asp-area="" asp-controller="Home" asp-action="Index">
                    Главная
                  </a>
                  <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Basket" asp-action="Index">Корзина<sup>@await Component.InvokeAsync("Bask")</sup></a>
                  <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Home" asp-action="Compare">Сравнение</a>
                  <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Home" asp-action="ShowFavorite">Избранное</a>
                </div>
            </div>
        </div>
        <div class="col-md-9 my-3">
            <div class="row">
                <div class="col-md-9 w-100">
                    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-indicators">
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                      </div>
                      <div class="carousel-inner">
                        <div class="carousel-item active">
                          <img src="https://gdr.one/simg/600x220/5094bd/fff?text=Picture" class="d-block w-100" alt="картинка 1">
                        </div>
                        <div class="carousel-item">
                          <img src="https://gdr.one/simg/600x220/5094bd/fff?text=Picture" class="d-block w-100" alt="картинка 2">
                        </div>
                        <div class="carousel-item">
                          <img src="https://gdr.one/simg/600x220/5094bd/fff?text=Picture" class="d-block w-100" alt="картинка 3">
                        </div>
                      </div>
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Предыдущий</span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Следующий</span>
                      </button>
                    </div>
                </div>
            </div>
            <div class="row my-2 px-2 d-flex justify-content-around">
            @foreach (var product in Model)
            {
                <div class="col-3 mx-1 mb-3 py-0 px-0 card-main">
                    <div class="card h-100 shadow">
                                    <div class="card-body d-flex flex-column">
                                        <a asp-controller="Product" asp-action="Index" asp-route-id="@product.Id"><img class="card-img-top" src="@product.Images.FirstOrDefault()?.Path"></a>
                                        <h3>@product.Name</h3>
                                        <h4>Цена: @product.Cost &#8381</h4>
                                        <div>
                                             <p id="1" class="cl1">@product.Description</p>
                                        </div>
                                            <div class="d-flex mt-auto">
                                                <div class="d-inline-flex">
                                                    <a asp-controller="Basket" asp-action="Adds" asp-route-productId="@product.Id" class="btn"><i class="fa-solid fa-cart-shopping fa-2x"></i></a>
                                                </div>
                                                    
                                                    @if (User.Identity.IsAuthenticated)
                                                    {
                                                        <div class="d-inline-flex mx-1">
                                                            @if (!product.Compare)
                                                            {
                                                                <a asp-controller="Home" asp-action="AddToComparsion" asp-route-productId="@product.Id" class="btn btn-info text-center btn-active">Сравнение</a>
                                                            }
                                                            else
                                                            {
                                                                <a asp-controller="Home" asp-action="DeleteFromComparsion" asp-route-productId="@product.Id" class="btn btn-danger btn-active">Удалить из сравнения</a>
                                                            }
                                                       </div>
                                                       <div class="d-inline-flex">
                                                            @if (!product.Favorite)
                                                            {
                                                                <a asp-controller="Home" asp-action="AddToFavorite" asp-route-productId="@product.Id" class="btn"><i class="fa-regular fa-heart fa-2x"></i></a>
                                                            }
                                                            else
                                                            {
                                                                 <a asp-controller="Home" asp-action="DeleteFromFavoriteIndex"  asp-route-productId="@product.Id" class="btn"><i class="fa-solid fa-heart fa-red-heart fa-2x"></i></a>
                                                            }
                                                        </div>
                                                    }
                                            </div>
                                    </div>
                                </div>
                            </div>
            }
            </div>
        </div>
    </div>

WebApplication1/Views/Home/Search.cshtml
@model List<ProductViewModel>

@if (Model == null || Model.Count() == 0)
{   
            <div class="d-flex flex-column">
                <div class="d-flex  justify-content-center ">
                    <h2>По вашему запросу товаров нет</h2>
                </div>
                <div class="d-flex  justify-content-center ">
                    <a asp-controller="Home" asp-action="Index" class="btn-active btn btn-light">На главную</a>
                </div>
            </div>
}
else
{    <div class="row">
        <div class="col-md-3 my-3">
            <div class="d-flex flex-column mb-2">
                <form method="post">
                    <div class="d-flex my-1">
                        <div class="input-group mb-3">
                          <input type="text" class="form-control" placeholder="Поиск по названию" aria-label="Поиск по названию" aria-describedby="basic-addon2" name="search">
                          <div class="input-group-append">
                              <button class="btn btn-outline-secondary" type="submit" asp-controller="Home" asp-action="Search"><i class="fa-solid fa-magnifying-glass"></i></button>
                          </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="d-flex flex-column mb-2">
                <div class="list-group">
                  <a class="list-group-item list-group-item-action active" asp-area="" asp-controller="Home" asp-action="Index">
                    Главная
                  </a>
                  <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Basket" asp-action="Index">Корзина<sup>@await Component.InvokeAsync("Bask")</sup></a>
                  <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Home" asp-action="Compare">Сравнение</a>
                  <a class="list-group-item list-group-item-action" asp-area="" asp-controller="Home" asp-action="ShowFavorite">Избранное</a>
                </div>
            </div>
        </div>
        <div class="col-md-9 my-3">
     <div class="row my-2 px-2 d-flex justify-content-around">
            @foreach (var product in Model)
            {
                            <div class="col-3 mx-1 mb-3 py-0 px-0 card-main">
                                <div class="card h-100 shadow">
                                    <div class="card-body d-flex flex-column">
                                        <a href="/product/index/@product.Id"><img class="card-img-top" src="@product.Images.FirstOrDefault()?.Path"></a>
                                        <h3>@product.Name</h3>
                                        <h4>Цена: @product.Cost &#8381</h4>
                                        <div>
                                             <p id="1" class="cl1">@product.Description</p>
                                        </div>
                                            <div class="d-flex mt-auto justify-content-around">
                                                <div class="d-inline-flex">
                                                    <a asp-controller="Basket" asp-action="Adds" asp-route-productId="@product.Id" class="btn"><i class="fa-solid fa-cart-shopping fa-2x"></i></a>
                                                </div>
                                                    <div class="d-inline-flex mx-1">
                                                    @if (true)
                                                    {
                                                        <a href="/home/addToComparsion?productId=@product.Id" class="btn btn-info text-center btn-active">Сравнение</a>
                                                    }
                                                    else
                                                    {
                                                         <a href="/home/addToComparsion?productId=@product.Id" class="btn btn-secondary disabled">Сравнение</a>
                                                    }
                                               </div>
                                               <div class="d-inline-flex">
                                                    @if (true)
                                                    {
                                                        <a href="/home/AddToFavorite?productId=@product.Id" class="btn"><i class="fa-regular fa-heart fa-2x"></i></a>
                                                    }
                                                    else
                                                    {
                                                         <a href="/home/DeleteFromFavoriteIndex?productId=@product.Id" class="btn"><i class="fa-solid fa-heart fa-red-heart fa-2x"></i></a>
                                                    }
                                                </div>
                                            </div>
                                    </div>
                                </div>
                            </div>
            }
     </div>
     </div>
     </div>
}